from flask import Flask

web = Flask(__name__)


@web.route("/<string:name>")
def home(name):
    return f'Hello {name}\n'


@web.route("/export")
def export():
    return """<?xml version="1.0" encoding="UTF-8"?>
<Table>
  <Rows>
    <Row>
      <WIC_NUM>1817771-2003468483-1</WIC_NUM>
      <WIC_CASE_NUM>1817771</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-30T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-12-03T00:00:00</WIC_DT_END>
      <WIC_STATUS>A</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>МЕЛЬНИЧУК</NP_SURNAME>
      <NP_NAME>ВЕРОНІКА</NP_NAME>
      <NP_PATRONYMIC>СТЕПАНІВНА</NP_PATRONYMIC>
      <NP_NUMIDENT>3078714906</NP_NUMIDENT>
      <NP_DOC_NUM>КР616885</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1797972-2003426651-1</WIC_NUM>
      <WIC_CASE_NUM>1797972</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-29T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-12-19T00:00:00</WIC_DT_END>
      <WIC_STATUS>A</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>БОДНАР</NP_SURNAME>
      <NP_NAME>ВАСИЛЬ</NP_NAME>
      <NP_PATRONYMIC>ІЛЛІЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>2331215376</NP_NUMIDENT>
      <NP_DOC_NUM>КР466371</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1759027-2003352576-1</WIC_NUM>
      <WIC_CASE_NUM>1759027</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-26T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-30T00:00:00</WIC_DT_END>
      <WIC_STATUS>A</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>СМЕТАНЮК</NP_SURNAME>
      <NP_NAME>КОСТЯНТИН</NP_NAME>
      <NP_PATRONYMIC>ДМИТРОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>3711709018</NP_NUMIDENT>
      <NP_DOC_NUM>006033278</NP_DOC_NUM>
      <NP_PDT>2</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1643262-2003362072-1</WIC_NUM>
      <WIC_CASE_NUM>1643262</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-24T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-12-02T00:00:00</WIC_DT_END>
      <WIC_STATUS>A</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ХАРИТОН</NP_SURNAME>
      <NP_NAME>МИХАЙЛО</NP_NAME>
      <NP_PATRONYMIC>ВАСИЛЬОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>2187404592</NP_NUMIDENT>
      <NP_DOC_NUM>КР093929</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1716010-2003245283-1</WIC_NUM>
      <WIC_CASE_NUM>1716010</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-24T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-30T00:00:00</WIC_DT_END>
      <WIC_STATUS>A</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ЮРЧУК</NP_SURNAME>
      <NP_NAME>ПЕТРО</NP_NAME>
      <NP_PATRONYMIC>МИКОЛАЙОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>2795020659</NP_NUMIDENT>
      <NP_DOC_NUM>КР111429</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1431626-2003235776-1</WIC_NUM>
      <WIC_CASE_NUM>1431626</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-24T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-12-02T00:00:00</WIC_DT_END>
      <WIC_STATUS>A</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>СОПРОВИЧ</NP_SURNAME>
      <NP_NAME>ВАСИЛЬ</NP_NAME>
      <NP_PATRONYMIC>ВАСИЛЬОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>2426710590</NP_NUMIDENT>
      <NP_DOC_NUM>КР459057</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1805917-2003443387-1</WIC_NUM>
      <WIC_CASE_NUM>1805917</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-23T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-12-03T00:00:00</WIC_DT_END>
      <WIC_STATUS>A</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ЦЮПА</NP_SURNAME>
      <NP_NAME>ВАЛЕРІЙ</NP_NAME>
      <NP_PATRONYMIC>АНАТОЛІЙОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>2542513758</NP_NUMIDENT>
      <NP_DOC_NUM>КР848899</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1369995-2003224727-1</WIC_NUM>
      <WIC_CASE_NUM>1369995</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-23T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-25T00:00:00</WIC_DT_END>
      <WIC_STATUS>A</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ВАСИЛІКА</NP_SURNAME>
      <NP_NAME>АНДРІЙ</NP_NAME>
      <NP_PATRONYMIC>ІВАНОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>3504413532</NP_NUMIDENT>
      <NP_DOC_NUM>КТ067436</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1589621-2003173498-1</WIC_NUM>
      <WIC_CASE_NUM>1589621</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-23T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-29T00:00:00</WIC_DT_END>
      <WIC_STATUS>A</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ПОПОВ</NP_SURNAME>
      <NP_NAME>ІЛЛЯ</NP_NAME>
      <NP_PATRONYMIC>ВІКТОРОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>3015017255</NP_NUMIDENT>
      <NP_DOC_NUM>КР459650</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1402852-2003118628-1</WIC_NUM>
      <WIC_CASE_NUM>1402852</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-20T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-22T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ГОВДА</NP_SURNAME>
      <NP_NAME>ДАРИНА</NP_NAME>
      <NP_PATRONYMIC>ЯРОСЛАВІВНА</NP_PATRONYMIC>
      <NP_NUMIDENT>2107403423</NP_NUMIDENT>
      <NP_DOC_NUM>КР255164</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1504233-2003069592-1</WIC_NUM>
      <WIC_CASE_NUM>1504233</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-20T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-22T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>МІРЕНЮК</NP_SURNAME>
      <NP_NAME>ГАННА</NP_NAME>
      <NP_PATRONYMIC>МИХАЙЛІВНА</NP_PATRONYMIC>
      <NP_NUMIDENT>2203715781</NP_NUMIDENT>
      <NP_DOC_NUM>КР505284</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1643262-2003107700-1</WIC_NUM>
      <WIC_CASE_NUM>1643262</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-19T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-23T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ХАРИТОН</NP_SURNAME>
      <NP_NAME>МИХАЙЛО</NP_NAME>
      <NP_PATRONYMIC>ВАСИЛЬОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>2187404592</NP_NUMIDENT>
      <NP_DOC_NUM>КР093929</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1369995-2003000859-1</WIC_NUM>
      <WIC_CASE_NUM>1369995</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-18T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-22T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ВАСИЛІКА</NP_SURNAME>
      <NP_NAME>АНДРІЙ</NP_NAME>
      <NP_PATRONYMIC>ІВАНОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>3504413532</NP_NUMIDENT>
      <NP_DOC_NUM>КТ067436</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1517018-2003003843-1</WIC_NUM>
      <WIC_CASE_NUM>1517018</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-17T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-22T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ІВАНОВИЧ</NP_SURNAME>
      <NP_NAME>ВАЛЕРІЙ</NP_NAME>
      <NP_PATRONYMIC>ІВАНОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>2537219090</NP_NUMIDENT>
      <NP_DOC_NUM>КР136586</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1593358-2002975340-1</WIC_NUM>
      <WIC_CASE_NUM>1593358</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-17T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-22T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>БИБИК</NP_SURNAME>
      <NP_NAME>ІГОР</NP_NAME>
      <NP_PATRONYMIC>ФЕДОРОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>2256711870</NP_NUMIDENT>
      <NP_DOC_NUM>КР001628</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1589621-2002967882-1</WIC_NUM>
      <WIC_CASE_NUM>1589621</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-17T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-22T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ПОПОВ</NP_SURNAME>
      <NP_NAME>ІЛЛЯ</NP_NAME>
      <NP_PATRONYMIC>ВІКТОРОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>3015017255</NP_NUMIDENT>
      <NP_DOC_NUM>КР459650</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1578312-2002943141-1</WIC_NUM>
      <WIC_CASE_NUM>1578312</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-16T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-25T00:00:00</WIC_DT_END>
      <WIC_STATUS>A</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>БАСІСТЕЙ</NP_SURNAME>
      <NP_NAME>ВАСИЛЬ</NP_NAME>
      <NP_PATRONYMIC>ДАНИЛОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>2078312137</NP_NUMIDENT>
      <NP_DOC_NUM>КР460259</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1577603-2002941596-2</WIC_NUM>
      <WIC_CASE_NUM>1577603</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-16T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-29T00:00:00</WIC_DT_END>
      <WIC_STATUS>A</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ДЕРУС</NP_SURNAME>
      <NP_NAME>ОЛЕКСАНДР</NP_NAME>
      <NP_PATRONYMIC>ГЕННАДІЙОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>2348914294</NP_NUMIDENT>
      <NP_DOC_NUM>КР559738</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1602420-2002994129-1</WIC_NUM>
      <WIC_CASE_NUM>1602420</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-14T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-24T00:00:00</WIC_DT_END>
      <WIC_STATUS>A</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ГУШУВАТА</NP_SURNAME>
      <NP_NAME>ЛЮДМИЛА</NP_NAME>
      <NP_PATRONYMIC>ВІКТОРІВНА</NP_PATRONYMIC>
      <NP_NUMIDENT>3619909829</NP_NUMIDENT>
      <NP_DOC_NUM>КТ141791</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1402852-2002826172-1</WIC_NUM>
      <WIC_CASE_NUM>1402852</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-13T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-19T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ГОВДА</NP_SURNAME>
      <NP_NAME>ДАРИНА</NP_NAME>
      <NP_PATRONYMIC>ЯРОСЛАВІВНА</NP_PATRONYMIC>
      <NP_NUMIDENT>2107403423</NP_NUMIDENT>
      <NP_DOC_NUM>КР255164</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1369995-2002823245-1</WIC_NUM>
      <WIC_CASE_NUM>1369995</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-13T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-17T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ВАСИЛІКА</NP_SURNAME>
      <NP_NAME>АНДРІЙ</NP_NAME>
      <NP_PATRONYMIC>ІВАНОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>3504413532</NP_NUMIDENT>
      <NP_DOC_NUM>КТ067436</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1444595-2002773541-1</WIC_NUM>
      <WIC_CASE_NUM>1444595</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-13T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-21T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ЦЕРНЮК</NP_SURNAME>
      <NP_NAME>СВІТЛАНА</NP_NAME>
      <NP_PATRONYMIC>МИХАЙЛІВНА</NP_PATRONYMIC>
      <NP_NUMIDENT>2336815245</NP_NUMIDENT>
      <NP_DOC_NUM>КР460017</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1517018-2002824764-1</WIC_NUM>
      <WIC_CASE_NUM>1517018</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-12T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-16T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ІВАНОВИЧ</NP_SURNAME>
      <NP_NAME>ВАЛЕРІЙ</NP_NAME>
      <NP_PATRONYMIC>ІВАНОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>2537219090</NP_NUMIDENT>
      <NP_DOC_NUM>КР136586</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1499157-2002757851-1</WIC_NUM>
      <WIC_CASE_NUM>1499157</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-12T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-16T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>СМЕТАНЮК</NP_SURNAME>
      <NP_NAME>КОСТЯНТИН</NP_NAME>
      <NP_PATRONYMIC>ДМИТРОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>3711709018</NP_NUMIDENT>
      <NP_DOC_NUM>006033278</NP_DOC_NUM>
      <NP_PDT>2</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1499073-2002757558-1</WIC_NUM>
      <WIC_CASE_NUM>1499073</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-12T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-16T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>КРАЙНЮК</NP_SURNAME>
      <NP_NAME>СЕРГІЙ</NP_NAME>
      <NP_PATRONYMIC>ІВАНОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>2213112772</NP_NUMIDENT>
      <NP_DOC_NUM>КР285014</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1504233-2002777388-1</WIC_NUM>
      <WIC_CASE_NUM>1504233</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-11T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-19T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>МІРЕНЮК</NP_SURNAME>
      <NP_NAME>ГАННА</NP_NAME>
      <NP_PATRONYMIC>МИХАЙЛІВНА</NP_PATRONYMIC>
      <NP_NUMIDENT>2203715781</NP_NUMIDENT>
      <NP_DOC_NUM>КР505284</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1444595-2002633622-1</WIC_NUM>
      <WIC_CASE_NUM>1444595</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-09T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-12T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ЦЕРНЮК</NP_SURNAME>
      <NP_NAME>СВІТЛАНА</NP_NAME>
      <NP_PATRONYMIC>МИХАЙЛІВНА</NP_PATRONYMIC>
      <NP_NUMIDENT>2336815245</NP_NUMIDENT>
      <NP_DOC_NUM>КР460017</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1431626-2002606319-1</WIC_NUM>
      <WIC_CASE_NUM>1431626</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-09T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-23T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>СОПРОВИЧ</NP_SURNAME>
      <NP_NAME>ВАСИЛЬ</NP_NAME>
      <NP_PATRONYMIC>ВАСИЛЬОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>2426710590</NP_NUMIDENT>
      <NP_DOC_NUM>КР459057</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1402852-2002551202-1</WIC_NUM>
      <WIC_CASE_NUM>1402852</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-09T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-12T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ГОВДА</NP_SURNAME>
      <NP_NAME>ДАРИНА</NP_NAME>
      <NP_PATRONYMIC>ЯРОСЛАВІВНА</NP_PATRONYMIC>
      <NP_NUMIDENT>2107403423</NP_NUMIDENT>
      <NP_DOC_NUM>КР255164</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1318784-2002540946-1</WIC_NUM>
      <WIC_CASE_NUM>1318784</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-09T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-09T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ГУЛЬПАК</NP_SURNAME>
      <NP_NAME>ОЛЕГ</NP_NAME>
      <NP_PATRONYMIC>ІВАНОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>3221408338</NP_NUMIDENT>
      <NP_DOC_NUM>КР830620</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1279671-2002513900-1</WIC_NUM>
      <WIC_CASE_NUM>1279671</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-09T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-15T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ШТЕФАНІЦА</NP_SURNAME>
      <NP_NAME>МИХАЙЛО</NP_NAME>
      <NP_PATRONYMIC>ДМИТРОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>2190908772</NP_NUMIDENT>
      <NP_DOC_NUM>КР165589</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1384596-2002516934-1</WIC_NUM>
      <WIC_CASE_NUM>1384596</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-08T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-10T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ЧУВАКОВ</NP_SURNAME>
      <NP_NAME>ЮРІЙ</NP_NAME>
      <NP_PATRONYMIC>ВОЛОДИМИРОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>3116519394</NP_NUMIDENT>
      <NP_DOC_NUM>ЧВ006539</NP_DOC_NUM>
      <NP_PDT>5</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1369995-2002490403-1</WIC_NUM>
      <WIC_CASE_NUM>1369995</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-08T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-12T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ВАСИЛІКА</NP_SURNAME>
      <NP_NAME>АНДРІЙ</NP_NAME>
      <NP_PATRONYMIC>ІВАНОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>3504413532</NP_NUMIDENT>
      <NP_DOC_NUM>КТ067436</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1402872-2002550639-1</WIC_NUM>
      <WIC_CASE_NUM>1402872</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-07T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-15T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>БАСІСТЕЙ</NP_SURNAME>
      <NP_NAME>ВАСИЛЬ</NP_NAME>
      <NP_PATRONYMIC>ДАНИЛОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>2078312137</NP_NUMIDENT>
      <NP_DOC_NUM>КР460259</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1481753-2002712133-1</WIC_NUM>
      <WIC_CASE_NUM>1481753</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-06T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-10T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>РИНЖУК</NP_SURNAME>
      <NP_NAME>ІВАН</NP_NAME>
      <NP_PATRONYMIC>МИКОЛАЙОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>2134014352</NP_NUMIDENT>
      <NP_DOC_NUM>КР634030</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1163257-2002697443-1</WIC_NUM>
      <WIC_CASE_NUM>1163257</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-06T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-13T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>БАНАР</NP_SURNAME>
      <NP_NAME>ОКСАНА</NP_NAME>
      <NP_PATRONYMIC>ІЛЛІВНА</NP_PATRONYMIC>
      <NP_NUMIDENT>2831923800</NP_NUMIDENT>
      <NP_DOC_NUM>КР322769</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1344252-2002423099-1</WIC_NUM>
      <WIC_CASE_NUM>1344252</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-05T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-09T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>АРІЙЧУК</NP_SURNAME>
      <NP_NAME>МИРОСЛАВ</NP_NAME>
      <NP_PATRONYMIC>КОРНІЙОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>2209111799</NP_NUMIDENT>
      <NP_DOC_NUM>КР238153</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1135385-2002355217-1</WIC_NUM>
      <WIC_CASE_NUM>1135385</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-05T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-08T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>МАЛЮСКИЙ</NP_SURNAME>
      <NP_NAME>МИКОЛА</NP_NAME>
      <NP_PATRONYMIC>ВІКТОРОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>3048213974</NP_NUMIDENT>
      <NP_DOC_NUM>КР505675</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>785285-2002387057-1</WIC_NUM>
      <WIC_CASE_NUM>785285</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-04T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-05T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>НЄМЦЕВА</NP_SURNAME>
      <NP_NAME>ЛЕНІНА</NP_NAME>
      <NP_PATRONYMIC>ГЕОРГІЇВНА</NP_PATRONYMIC>
      <NP_NUMIDENT>2235314561</NP_NUMIDENT>
      <NP_DOC_NUM>КР425868</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1318784-2002355769-1</WIC_NUM>
      <WIC_CASE_NUM>1318784</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-04T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-08T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ГУЛЬПАК</NP_SURNAME>
      <NP_NAME>ОЛЕГ</NP_NAME>
      <NP_PATRONYMIC>ІВАНОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>3221408338</NP_NUMIDENT>
      <NP_DOC_NUM>КР830620</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>582814-2001071179-1</WIC_NUM>
      <WIC_CASE_NUM>582814</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-04T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-07T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ЖИЖИЯН</NP_SURNAME>
      <NP_NAME>СЕРГІЙ</NP_NAME>
      <NP_PATRONYMIC>ВАСИЛЬОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>2775710317</NP_NUMIDENT>
      <NP_DOC_NUM>КР163353</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1185339-2002333753-1</WIC_NUM>
      <WIC_CASE_NUM>1185339</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-03T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-05T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>СЕМЕНОВ</NP_SURNAME>
      <NP_NAME>АНДРІЙ</NP_NAME>
      <NP_PATRONYMIC>ВОЛОДИМИРОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>2886716871</NP_NUMIDENT>
      <NP_DOC_NUM>КР017018</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1289100-2002301378-1</WIC_NUM>
      <WIC_CASE_NUM>1289100</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-03T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-10T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>БОГАТИРЕЦЬ</NP_SURNAME>
      <NP_NAME>ВІКТОР</NP_NAME>
      <NP_PATRONYMIC>ТІТУСОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>3158219255</NP_NUMIDENT>
      <NP_DOC_NUM>000840822</NP_DOC_NUM>
      <NP_PDT>2</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1279671-2002283424-1</WIC_NUM>
      <WIC_CASE_NUM>1279671</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-03T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-08T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ШТЕФАНІЦА</NP_SURNAME>
      <NP_NAME>МИХАЙЛО</NP_NAME>
      <NP_PATRONYMIC>ДМИТРОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>2190908772</NP_NUMIDENT>
      <NP_DOC_NUM>КР165589</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>992695-2002213577-1</WIC_NUM>
      <WIC_CASE_NUM>992695</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-03T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-19T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ЖУРАВЕЛЬ</NP_SURNAME>
      <NP_NAME>СВІТЛАНА</NP_NAME>
      <NP_PATRONYMIC>ІВАНІВНА</NP_PATRONYMIC>
      <NP_NUMIDENT>2637605244</NP_NUMIDENT>
      <NP_DOC_NUM>АА948465</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1402852-2002550602-1</WIC_NUM>
      <WIC_CASE_NUM>1402852</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-02T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-08T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ГОВДА</NP_SURNAME>
      <NP_NAME>ДАРИНА</NP_NAME>
      <NP_PATRONYMIC>ЯРОСЛАВІВНА</NP_PATRONYMIC>
      <NP_NUMIDENT>2107403423</NP_NUMIDENT>
      <NP_DOC_NUM>КР255164</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1163257-2002345278-1</WIC_NUM>
      <WIC_CASE_NUM>1163257</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-02T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-05T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>БАНАР</NP_SURNAME>
      <NP_NAME>ОКСАНА</NP_NAME>
      <NP_PATRONYMIC>ІЛЛІВНА</NP_PATRONYMIC>
      <NP_NUMIDENT>2831923800</NP_NUMIDENT>
      <NP_DOC_NUM>КР322769</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1269034-2002261530-1</WIC_NUM>
      <WIC_CASE_NUM>1269034</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-02T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-05T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>СМЕТАНЮК</NP_SURNAME>
      <NP_NAME>ЄВГЕНІЯ</NP_NAME>
      <NP_PATRONYMIC>ІВАНІВНА</NP_PATRONYMIC>
      <NP_NUMIDENT>2291612746</NP_NUMIDENT>
      <NP_DOC_NUM>КР373742</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1135385-2002199825-1</WIC_NUM>
      <WIC_CASE_NUM>1135385</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-02T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-04T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>МАЛЮСКИЙ</NP_SURNAME>
      <NP_NAME>МИКОЛА</NP_NAME>
      <NP_PATRONYMIC>ВІКТОРОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>3048213974</NP_NUMIDENT>
      <NP_DOC_NUM>КР505675</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>875009-2002191884-1</WIC_NUM>
      <WIC_CASE_NUM>875009</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-02T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-03T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ЧОБОТАР</NP_SURNAME>
      <NP_NAME>АНДРІЙ</NP_NAME>
      <NP_PATRONYMIC>ОРЕСТОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>2883617954</NP_NUMIDENT>
      <NP_DOC_NUM>КР022412</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1211663-2002157552-1</WIC_NUM>
      <WIC_CASE_NUM>1211663</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-01T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-09T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>РОШКО</NP_SURNAME>
      <NP_NAME>ЄВГЕН</NP_NAME>
      <NP_PATRONYMIC>ІГНАТОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>2460215652</NP_NUMIDENT>
      <NP_DOC_NUM>КТ076575</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1209932-2002154709-1</WIC_NUM>
      <WIC_CASE_NUM>1209932</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-11-01T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-06T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ДЕМЧИШИНА</NP_SURNAME>
      <NP_NAME>ОЛЕНА</NP_NAME>
      <NP_PATRONYMIC>ГЕОРГІЇВНА</NP_PATRONYMIC>
      <NP_NUMIDENT>2554209543</NP_NUMIDENT>
      <NP_DOC_NUM>КР164401</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>905957-2002269263-1</WIC_NUM>
      <WIC_CASE_NUM>905957</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-10-30T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-03T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>КОЗУБЕНКО</NP_SURNAME>
      <NP_NAME>ЛІЛІЯ</NP_NAME>
      <NP_PATRONYMIC>МИХАЙЛІВНА</NP_PATRONYMIC>
      <NP_NUMIDENT>2526516621</NP_NUMIDENT>
      <NP_DOC_NUM>КР188039</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>999255-2002078746-1</WIC_NUM>
      <WIC_CASE_NUM>999255</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-10-30T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-02T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>БУРМА</NP_SURNAME>
      <NP_NAME>АННА</NP_NAME>
      <NP_PATRONYMIC>СЕРГІЇВНА</NP_PATRONYMIC>
      <NP_NUMIDENT>3485802063</NP_NUMIDENT>
      <NP_DOC_NUM>005104941</NP_DOC_NUM>
      <NP_PDT>2</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>785285-2002072356-1</WIC_NUM>
      <WIC_CASE_NUM>785285</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-10-30T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-03T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>НЄМЦЕВА</NP_SURNAME>
      <NP_NAME>ЛЕНІНА</NP_NAME>
      <NP_PATRONYMIC>ГЕОРГІЇВНА</NP_PATRONYMIC>
      <NP_NUMIDENT>2235314561</NP_NUMIDENT>
      <NP_DOC_NUM>КР425868</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>882559-2002037442-1</WIC_NUM>
      <WIC_CASE_NUM>882559</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-10-30T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-09T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>САЛЬНІКОВ</NP_SURNAME>
      <NP_NAME>СЕРГІЙ</NP_NAME>
      <NP_PATRONYMIC>ІВАНОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>2200724391</NP_NUMIDENT>
      <NP_DOC_NUM>КР033265</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1185339-2002113248-1</WIC_NUM>
      <WIC_CASE_NUM>1185339</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-10-29T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-02T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>СЕМЕНОВ</NP_SURNAME>
      <NP_NAME>АНДРІЙ</NP_NAME>
      <NP_PATRONYMIC>ВОЛОДИМИРОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>2886716871</NP_NUMIDENT>
      <NP_DOC_NUM>КР017018</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1173390-2002074480-1</WIC_NUM>
      <WIC_CASE_NUM>1173390</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-10-29T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-05T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>РОМАНЮК</NP_SURNAME>
      <NP_NAME>ЯН</NP_NAME>
      <NP_PATRONYMIC>ВАСИЛЬОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>3254309934</NP_NUMIDENT>
      <NP_DOC_NUM>КР887244</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1163257-2002036255-1</WIC_NUM>
      <WIC_CASE_NUM>1163257</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-10-28T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-01T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>БАНАР</NP_SURNAME>
      <NP_NAME>ОКСАНА</NP_NAME>
      <NP_PATRONYMIC>ІЛЛІВНА</NP_PATRONYMIC>
      <NP_NUMIDENT>2831923800</NP_NUMIDENT>
      <NP_DOC_NUM>КР322769</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1135385-2001972511-1</WIC_NUM>
      <WIC_CASE_NUM>1135385</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-10-28T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-01T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>МАЛЮСКИЙ</NP_SURNAME>
      <NP_NAME>МИКОЛА</NP_NAME>
      <NP_PATRONYMIC>ВІКТОРОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>3048213974</NP_NUMIDENT>
      <NP_DOC_NUM>КР505675</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1126286-2001954341-1</WIC_NUM>
      <WIC_CASE_NUM>1126286</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-10-27T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-01T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ЧИНЧИК</NP_SURNAME>
      <NP_NAME>НАДІЯ</NP_NAME>
      <NP_PATRONYMIC>ВОЛОДИМИРІВНА</NP_PATRONYMIC>
      <NP_NUMIDENT>3120328068</NP_NUMIDENT>
      <NP_DOC_NUM>001150083</NP_DOC_NUM>
      <NP_PDT>2</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>992695-2001846055-1</WIC_NUM>
      <WIC_CASE_NUM>992695</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-10-27T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-02T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ЖУРАВЕЛЬ</NP_SURNAME>
      <NP_NAME>СВІТЛАНА</NP_NAME>
      <NP_PATRONYMIC>ІВАНІВНА</NP_PATRONYMIC>
      <NP_NUMIDENT>2637605244</NP_NUMIDENT>
      <NP_DOC_NUM>АА948465</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>1092019-2001882997-2</WIC_NUM>
      <WIC_CASE_NUM>1092019</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-10-26T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-12T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>БІЛОСКУРСЬКА</NP_SURNAME>
      <NP_NAME>ГАННА</NP_NAME>
      <NP_PATRONYMIC>ЛЕОПОЛЬДІВНА</NP_PATRONYMIC>
      <NP_NUMIDENT>2629607360</NP_NUMIDENT>
      <NP_DOC_NUM>КТ023429</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>875009-2001708795-1</WIC_NUM>
      <WIC_CASE_NUM>875009</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-10-23T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-01T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ЧОБОТАР</NP_SURNAME>
      <NP_NAME>АНДРІЙ</NP_NAME>
      <NP_PATRONYMIC>ОРЕСТОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>2883617954</NP_NUMIDENT>
      <NP_DOC_NUM>КР022412</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>661697-2001695715-1</WIC_NUM>
      <WIC_CASE_NUM>661697</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-10-23T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-12T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>БОДНАР</NP_SURNAME>
      <NP_NAME>ВАСИЛЬ</NP_NAME>
      <NP_PATRONYMIC>ІЛЛІЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>2331215376</NP_NUMIDENT>
      <NP_DOC_NUM>КР466371</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>880137-2001468693-1</WIC_NUM>
      <WIC_CASE_NUM>880137</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-10-19T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-05T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ЛИСАН</NP_SURNAME>
      <NP_NAME>ДМИТРО</NP_NAME>
      <NP_PATRONYMIC>ГЕОРГІЙОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>2102603811</NP_NUMIDENT>
      <NP_DOC_NUM>КР493031</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
    <Row>
      <WIC_NUM>2000914528-1</WIC_NUM>
      <WIC_CASE_NUM>582814</WIC_CASE_NUM>
      <WIC_DT_BEGIN>2021-10-05T00:00:00</WIC_DT_BEGIN>
      <WIC_DT_END>2021-11-03T00:00:00</WIC_DT_END>
      <WIC_STATUS>P</WIC_STATUS>
      <WIC_CD>1</WIC_CD>
      <WIC_CD_Name>Тимчасова непрацездатність внаслідок захворювання або травми, що не пов’язані з нещасним випадком на виробництві</WIC_CD_Name>
      <SIGN_ANLK_NARKOTIK_INTOXICATION>false</SIGN_ANLK_NARKOTIK_INTOXICATION>
      <VIOLATION_EXTENSION>false</VIOLATION_EXTENSION>
      <NP_SURNAME>ЖИЖИЯН</NP_SURNAME>
      <NP_NAME>СЕРГІЙ</NP_NAME>
      <NP_PATRONYMIC>ВАСИЛЬОВИЧ</NP_PATRONYMIC>
      <NP_NUMIDENT>2775710317</NP_NUMIDENT>
      <NP_DOC_NUM>КР163353</NP_DOC_NUM>
      <NP_PDT>1</NP_PDT>
    </Row>
  </Rows>
</Table>"""


if __name__ == '__main__':
    web.run(port=9999, debug=True)
